# Generated by Django 5.1.7 on 2025-05-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vending_api', '0002_sale_sale_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendingmachines',
            name='vending_type',
            field=models.CharField(choices=[('card', 'С оплатой картой'), ('cash', 'С оплатой наличными'), ('card-cahs', 'Два вида оплаты')], default='card', max_length=10, verbose_name='Тип аппарата по способу оплаты'),
        ),
    ]
