# Generated by Django 5.1.7 on 2025-05-09 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Уникальный идентификатор товара')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('quantity_in_stock', models.PositiveIntegerField(verbose_name='Количество в наличии')),
                ('min_stock', models.PositiveIntegerField(verbose_name='Минимальный запас')),
                ('sales_trends', models.FloatField(verbose_name='Склонности к продажам')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Уникальный идентификатор пользователя')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО пользователя')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('operator', 'Оператор')], max_length=10, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='VendingMachines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendingID', models.CharField(max_length=355, verbose_name='ID аппарата')),
                ('address', models.CharField(max_length=355, verbose_name='Адрес или описание места установки устройства')),
                ('vending_name', models.CharField(max_length=100, verbose_name='Название аппарата')),
                ('vending_modem', models.CharField(max_length=55, verbose_name='Модем')),
                ('vending_model', models.CharField(max_length=355, verbose_name='Указание на марку и модель вендингового аппарата')),
                ('vending_type', models.CharField(choices=[('card', 'С оплатой картой'), ('cash', 'С оплатой наличными'), ('both', 'Два вида оплаты')], default='card', max_length=10, verbose_name='Тип аппарата по способу оплаты')),
                ('vending_status', models.CharField(choices=[('working', 'Рабочий'), ('not_working', 'Не рабочий'), ('in_service', 'На обслуживании')], default='working', max_length=20, verbose_name='Статус аппарата')),
                ('date_of_installation', models.DateField(verbose_name='Дата установки')),
                ('date_of_last_maintenance', models.DateField(verbose_name='Дата последнего обслуживания')),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Общая сумма продаж')),
            ],
            options={
                'verbose_name': 'Вендинговый аппарат',
                'verbose_name_plural': 'Вендинговые аппараты',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Уникальный идентификатор записи о продаже')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время продажи')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('QR', 'QR')], default='card', max_length=10, verbose_name='Метод оплаты')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vending_api.product', verbose_name='ID товара')),
                ('vending_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='Vending_api.vendingmachines', verbose_name='Вендинговый аппарат')),
            ],
            options={
                'verbose_name': 'Продажи',
                'verbose_name_plural': 'Продажи',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('maintenanceID', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Уникальный идентификатор записи о обслуживании')),
                ('maintenance_date', models.DateField(verbose_name='Дата обслуживания')),
                ('work_description', models.TextField(verbose_name='Описание работы')),
                ('problems_identified', models.TextField(blank=True, verbose_name='Проблемы')),
                ('executor', models.CharField(max_length=255, verbose_name='Исполнитель')),
                ('vending_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vending_api.vendingmachines', verbose_name='ID аппарата')),
            ],
            options={
                'verbose_name': 'Обслуживание',
                'verbose_name_plural': 'Обслуживание',
            },
        ),
    ]
